--Clienti(idCliente(pk),cognome,nome,indirizzo,email,telefono,idCitta(fk))
--Citta(idCitta(pk),citta,CAP)
--Pacchi(codSpedizione(pk),tipo,peso,dimesione,dataSpedizione,idMITTENTE(fk,refClienti(pk)),idDESTINATARIO(fk,refClienti(pk)))

--CREATE TABLE CITTA(
--IDCITTA INT PRIMARY KEY IDENTITY(1,1),
--CITTA VARCHAR(50) NOT NULL,
--CAP VARCHAR(5) NOT NULL);

--CREATE TABLE CLIENTI(
--IDCLIENTE INT PRIMARY KEY IDENTITY(1,1),
--COGNOME VARCHAR(30) NOT NULL,
--NOME VARCHAR(30) NOT NULL,
--INDIRIZZO VARCHAR(50) NOT NULL,
--EMAIL VARCHAR(50) NOT NULL,
--TELEFONO VARCHAR(10) NOT NULL,
--IDCITTA INT FOREIGN KEY REFERENCES CITTA(IDCITTA) NOT NULL);

--CREATE TABLE PACCHI(
--CODSPEDIZIONE INT PRIMARY KEY IDENTITY(1,1),
--TIPO VARCHAR(10),
--PESO FLOAT DEFAULT(1),
--DIMENSIONE VARCHAR(10),
--DATASPEDIZIONE DATE DEFAULT(GETDATE()),
--IDMITTENTE INT FOREIGN KEY REFERENCES CLIENTI(IDCLIENTE) NOT NULL,
--IDDESTINATARIO INT FOREIGN KEY REFERENCES CLIENTI(IDCLIENTE) NOT NULL);

INSERT INTO 
	CITTA(CITTA,CAP) 
VALUES
	('FOSSANO',12045),
	('SAVIGLIANO',12038),
	('BENE VAGIENNA',12041),
	('TORINO_STARTS',10121),
	('TORINO_ENDS',10156);
INSERT INTO 
	CLIENTI(COGNOME,NOME,INDIRIZZO,EMAIL,TELEFONO,IDCITTA)
VALUES
	('MASENTO','EMANUELE','VIVE A SAVIGLIANO','NON@LA.SO')
SELECT
	M.COGNOME +M.NOME AS 'MITTENTE',
	D.COGNOME +D.NOME AS 'DESTINATARIO'
FROM
	PACCHI P
LEFT JOIN
	CLIENTI M ON P.IDMITTENTE=M.IDCLIENTE
LEFT JOIN
	CLIENTI D ON P.IDDESTINATARIO=D.IDCLIENTE